config/routes.rb
Rails.application.routes.draw do
    root 'one#home'

    get 'about', to: 'one#about'

    post 'member', to: 'one#member'
    get 'signup', to: 'one#signup'

    get 'admin', to: 'one#admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/one_controller.rb
class OneController < ApplicationController
    def about
        render 'one/About.html.erb'
    end

    def member
        render 'one/member'
    end


    def admin
        render layout: 'adminLayout'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_navibar.html.erb
<ul>
    <li><a href="/"> home </a></li>
    <li><a href="/about"> about </a></li>
</ul>

app/views/layouts/adminLayout.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title> Admin 後台 </title>
    </head>
    <body>
        <ul>
            <li><a href="/"> home </a></li>
        </ul>

        <%= yield %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <%= render 'common/navibar' %>

    <%= yield %>
</body>
</html>

app/views/one/About.html.erb
<h1> About </h1>

app/views/one/admin.html.erb
<h1> Admin Page </h1>

app/views/one/home.html.erb
<h1> Home </h1>

<%= form_tag member_path do %>
    Account : <input type="text" name="account" value="Jian-Hau, Su"> </br>
    Password : <input type="password" name="password" value="1234"> </br>
    <input type="submit" value="log in">
<% end %>

app/views/one/member.html.erb
<h1> Member Root Page </h1>

name: <%= params[:account] %>


</br> </br> </br> <%= debug params %>

app/views/one/signup.html.erb
<h1> Sign Up Page </h1>

<%= form_tag member_path do %>
    Account : <input type="text" name="account" value="Jian-Hau, Su"> </br>
    Password : <input type="password" name="password" value="1234"> </br>
    Password Again : <input type="password" name="password" value="1234"> </br>
    <input type="submit" value="sign up">
<% end %>